### ISSUE TITLE
Is it possible to install nornir_netmiko on Nornir 3?

### ISSUE THREAD

**Issue by ericorain** [ktbyers/nornir_netmiko#1]
Dear Kirk,

I cannot install this plugin for nornir 3.

Here is what I get (from a clean python installation):
#######################################
D:\>pip freeze

D:\>pip install --pre "nornir>=3.0.0b0"
Collecting nornir>=3.0.0b0
  Downloading nornir-3.0.0b1-py3-none-any.whl (29 kB)
Collecting mypy_extensions<0.5.0,>=0.4.1
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting ruamel.yaml<0.17,>=0.16
  Using cached ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Collecting typing_extensions<4.0,>=3.7
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Using cached ruamel.yaml.clib-0.2.0.tar.gz (178 kB)
Using legacy 'setup.py install' for ruamel.yaml.clib, since package 'wheel' is not installed.
Installing collected packages: mypy-extensions, ruamel.yaml.clib, ruamel.yaml, typing-extensions, nornir
    Running setup.py install for ruamel.yaml.clib ... done
Successfully installed mypy-extensions-0.4.3 nornir-3.0.0b1 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 typing-extensions-3.7.4.2

D:\>pip freeze
mypy-extensions==0.4.3
nornir==3.0.0b1
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
typing-extensions==3.7.4.2

D:\>pip install nornir_netmiko
ERROR: Could not find a version that satisfies the requirement nornir_netmiko (from versions: none)
ERROR: No matching distribution found for nornir_netmiko

D:\>pip install nornir-netmiko
ERROR: Could not find a version that satisfies the requirement nornir-netmiko (from versions: none)
ERROR: No matching distribution found for nornir-netmiko

D:\>
#######################################

It seems that nornir_netmiko is not available at pypi and I suppose that it is the problem. Or maybe I am doing something wrong...

Kind regards.

**Comment by ktbyers** [comment]
Yes, it is not up on pypi yet. You would need to install it directly from the repository. I will probably try to get it up to pypi in the next week or so.


Regards, Kirk
