### ISSUE TITLE
netmiko.ssh_exception.NetmikoTimeoutException

### ISSUE THREAD

**Issue by avargasn** [ktbyers/nornir_netmiko#10]
I'm getting the following exception:
netmiko.ssh_exception.NetmikoTimeoutException: Paramiko: 'No existing session' error: try increasing 'conn_timeout' to 10 seconds or larger

And I'm getting the following exception by adding conn_timeout to netmiko_send_command:
TypeError: send_command_timing() got an unexpected keyword argument 'conn_timeout'

The task is the following:
def get_config(task: Task):
    try:
        result = task.run(
            task=netmiko_send_command,
            command_string="show configuration",
            use_timing=True,
            enable=True,
            conn_timeout=10
        )
    except:
        pass

**Comment by ktbyers** [comment]
`conn_timeout` is an argument to `ConnectHandler`.


Regards, Kirk
