### ISSUE TITLE
task send_config fails with nokia sros

### ISSUE THREAD

**Issue by Trasmontinho** [ktbyers/nornir_netmiko#13]
Hello @ktbyers , 

I'm facing some issues with Nornir task send config with Nokia routers. 

When I execute the task it drops me the error below : 

```
2021-02-25 09:28:13,651 - nornir.core.task -    ERROR -      start() - Host 'NOKIA_ROUTER': task 'Create the new user locally on nokia' failed with traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 25, in netmiko_send_config
    net_connect.enable()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/nokia/nokia_sros_ssh.py", line 87, in enable
    return super().enable(cmd=cmd, pattern=pattern, re_flags=re_flags)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1688, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.
```
this is normal as per itself my Nokia hasn't got enable-admin activated on it.

Do you think that supply an extra argument to pass on enable mode or not could be a solution to fix it ?  

The send_config_set (out of nornir task) works perfectly by the way.

the output when you try to type enable-admin on the router in my case : 
```
*A:NOKIA_ROUTER# enable-admin 
MINOR: CLI Cannot enable admin mode since the admin password is not configured.
```

Regards,

Sam

**Comment by Trasmontinho** [comment]
Hello @ktbyers ,

Have you a chance to look to this issue and give me your recos to it ? 3

Thanks,

Regards,
Sam

**Comment by ktbyers** [comment]
@Trasmontinho Sorry for the delayed response--let's add a `enable_mode=True` argument to `netmiko_send_config`.

The default will be enable_mode=True and it will do what it currently does.

If `enable_mode=False` then the `enable()` call will be skipped/bypassed.

Do you want to do a PR on this?

**Comment by Trasmontinho** [comment]
I think it's a good idea to do like that. Like that other devices where enable mode is not available will be compatible with this task.

I can submit it if you want. 

Sam

**Comment by ktbyers** [comment]
Okay, sounds good.

**Comment by Trasmontinho** [comment]
pull request submitted : [71856ad](url)

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/ktbyers/nornir_netmiko/pull/15
