### ISSUE TITLE
task_send_config fails for F5 tmsh

### ISSUE THREAD

**Issue by Trasmontinho** [ktbyers/nornir_netmiko#14]
Hello, 

It's me again :-)

An other issue with the task_send_config. 

F5 hasn't enable mode. 

the fact is the base_prompt is not always the same (depending in actions your doing).

due to that, I've got the error below : 

Traceback (most recent call last):
```
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 570, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 25, in netmiko_send_config
    net_connect.enable()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1675, in enable
    if not self.check_enable_mode():
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 1650, in check_enable_mode
    output = self.read_until_prompt()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 648, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 581, in _read_channel_expect
    "Timed-out reading channel, data not available."
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```
I've  fix temporarely the problem with a new method  for `check_enable_mode returning true` in the F5 plugin. But I'm not sure that's the good way. 

What do you think about that ?

**Comment by Trasmontinho** [comment]
Hello @ktbyers ,
 
Have you a chance to look to this issue and give me your recos to it ? 3

Thanks,

Regards, 
Sam

**Comment by ktbyers** [comment]
@Trasmontinho Does adding the `enable_mode` argument as per #13 fix this?

I think we should also add the following into the Netmiko F5 tmsh driver:

```python
    def check_enable_mode(self, check_string: str = "") -> bool:
        """Platform does not have an enable mode."""
        return True

    def enable(
        self, cmd: str = "", pattern: str = "ssword", re_flags: int = re.IGNORECASE
    ) -> str:
        """Platform does not have an enable mode."""
        return ""

    def exit_enable_mode(self, exit_command: str = "") -> str:
        """Platform does not have an enable mode."""
        return ""
```

Do you want to submit this PR or do you want me to do it?

Can you explain/expand upon this statement?

`the fact is the base_prompt is not always the same (depending in actions your doing).`

**Comment by Trasmontinho** [comment]
Hello @ktbyers, 

Up to you. If you don't have time for it, I can submit it.

regarding the point `the fact is the base_prompt is not always the same (depending in actions your doing)` Let me give you an example to be more explicit : 
Let's assume that your acting in a F5 cluster and that is in sync. You will set the base prompt as below : 
`trasmontinho@(f5-a)(cfg-sync In Sync)(Active)(/Common)(tmos)# `
As soon as you apply a configuration on a F5 cluster mode, the prompt is as : 
'trasmontinho@(f5-a)(cfg-sync Changes Pending)(Active)(/Common)(tmos)# '

**Comment by ktbyers** [comment]
Okay probably should just put in a separate handler in netmiko that sets base_prompt to just the end of this:

```
(tmos)
```

So we don't care about anything that changes in the prompt.

**Comment by Trasmontinho** [comment]
I'll move the story about the prompt changes on netmiko. 

Regarding the initial issue the pull request that I've submitted should resolve the send_config fails. Let me have a try about it.

**Comment by Trasmontinho** [comment]
Ok after some testing the enable parameter solve the problem. 

I'll add anyway the code below to the f5 plugin and have a look to this story of the prompt. I'll keep you posted.

 ```
def check_enable_mode(self, check_string: str = "") -> bool:
        """Platform does not have an enable mode."""
        return True

    def enable(
        self, cmd: str = "", pattern: str = "ssword", re_flags: int = re.IGNORECASE
    ) -> str:
        """Platform does not have an enable mode."""
        return ""

    def exit_enable_mode(self, exit_command: str = "") -> str:
        """Platform does not have an enable mode."""
        return ""
```
