### ISSUE TITLE
Feature request: Exit config mode task or call task

### ISSUE THREAD

**Issue by dmulyalin** [ktbyers/nornir_netmiko#18]
Hi,

Noticed that after commit IOS XR does not exit configuration mode, there is `exit_config_mode` method available for iosxr driver, but no task exists to call that method, should we create such a task?

Alternatively, instead of codifying methods in dedicated task plugins, can create `call` task plugin to execute any arbitrary method on `conn` object.

Can help with pull request but not sure which way is more preferred.

**Comment by ktbyers** [comment]
https://github.com/ktbyers/nornir_netmiko/pull/24
