### ISSUE TITLE
Nornir-netmiko receiving "paramiko.buffered_pipe.PipeTimeout" after delay in tasks

### ISSUE THREAD

**Issue by ozschmoz** [ktbyers/nornir_netmiko#29]
Hi, I was wondering if you could give any hints to an issue I'm having. I access Dell OS6 switch with nornir_netmiko but if I delay task execution while the connection is established I receive "paramiko.buffered_pipe.PipeTimeout". I noticed that if I don't leave my connection idle for more than 10 seconds I can execute my tasks normally (mostly) either that or it's because it is lagging in response due to higher load. Is there something I could do to increase wait timeouts?
hosts.yaml
```
dell_sw:
    hostname: 'dell_sw'
    platform: 'dell_os6'
    port: 22
    connection_options:
        netmiko:
            extras:
                conn_timeout: 60
```

I'd like to keep the connection to the switch open while tasks are being sent to my queue and only close once there was no tasks in the last 20 seconds.

```
def multiple_tasks(task: Task,info):
	task.run(
			name="switch_task",
			task=netmiko_send_config,
			config_commands = info,
	)


nr = InitNornir(config_file="config.yaml")
nr = nr.filter(name="dell_sw")
q2 = queue.Queue()
t0 = time.time()

while (time.time() - t0) < 20:
		if not q2.empty():
				sw_task = q2.get()
				results = nr.run(
						task=multiple_tasks, info=sw_task
				)
				t0 = time.time()
nr.close_connections(nr.inventory.hosts)
```

error that I receive:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 573, in _read_channel_expect
    new_data = self.remote_conn.recv(MAX_BUFFER)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 701, in recv
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_netmiko/tasks/netmiko_send_config.py", line 36, in netmiko_send_config
    net_connect.enable()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 24, in enable
    return super().enable(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1682, in enable
    if not self.check_enable_mode():
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 14, in check_enable_mode
    return super().check_enable_mode(check_string=check_string)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1655, in check_enable_mode
    output = self.read_until_prompt()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 651, in read_until_prompt
    return self._read_channel_expect(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 583, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.
```

nornir==3.2.0
nornir-netmiko==0.1.2
nornir-utils==0.1.2

**Comment by ktbyers** [comment]
The failure above looks like it is calling `enable()` mode and that is failing.

In particular, it looks like it is checking if it is in enable mode or not and is trying to read (looking for the router prompt) and this is never coming back.

I would probably look at the Netmiko session_log to see if you got more details about what is happing here.

This doesn't really answer what you were asking about timeouts, but Netmiko/Nornir shouldn't close the connection (unless you tell it to close or the switch closes it).

You should be able to do this for the session_log:

```yaml
dell_sw:
    hostname: 'dell_sw'
    platform: 'dell_os6'
    port: 22
    connection_options:
        netmiko:
            extras:
                conn_timeout: 60
                session_log: output.txt
```

**Comment by ozschmoz** [comment]
@ktbyers  Thank you so much for your input and sorry for not replying sooner. It appears it happens due to the increased load on switch management. I ran the same "acl add" task multiple times and sometimes it would pass normally and sometimes it would crash with the above mentioned error. I also tried to log into switch manually during paramiko task and I noticed console lag. Is it possible to take into consideration the lag of switch when executing tasks?

Ran this procedure 5 times in a row on a single connection (also there was additional connection from a different telnet script at the same time):

['ip access-list ACL_test1', '1010 permit ip 10.2.2.19 0.0.0.0 any', '1020 permit ip 10.170.192.0 0.0.0.255 any', '1030 permit ip 192.168.90.10 0.0.0.0 any', 'exit', 'interface gi1/0/41', 'ip access-group ACL_test1 in 10', 'exit']

**Comment by ktbyers** [comment]
You could try adding:

```yaml
dell_sw:
    hostname: 'dell_sw'
    platform: 'dell_os6'
    port: 22
    connection_options:
        netmiko:
            extras:
                conn_timeout: 60
                session_log: output.txt
                fast_cli: False
                global_delay_factor: 2           # or alternatively 4
```

And see if that helps.

Let me know what you find.

**Comment by ozschmoz** [comment]
It seems to alleviate the issue as I don't get as many connection breaks, but it is still there. It seems like multiple logged in users put a strain on its performance. I have old perl scripts running and changing configuration through telnet and then at the end doing "write" which seems like the biggest slowdown of management. Oddly enough my old perl scripts that work through telnet never fail, they just take a bit some time to complete.

I have 2 x N2048 stacked switches so every config change ends with a sync command. I will check if maybe there's anything I can tune in settings as well as firmware updates. I might end up writing better checks for failed tasks and then just re-run them. Thank you for you suggestion.
