### ISSUE TITLE
ValueError: Router prompt not found: '[sudo] password for 

### ISSUE THREAD

**Issue by jbl241987** [ktbyers/nornir_netmiko#4]
I am trying to connect with Linux server and execute some culr commands using netmiko. But I am getting subjected error. Host platform is - linux

```python
from nornir import InitNornir
from nornir_utils.plugins.functions import print_title, print_result
from nornir_netmiko.tasks import netmiko_send_config, netmiko_commit, netmiko_send_command
from nornir_utils.plugins.processors import PrintResult
from nornir_utils.plugins.tasks.data import load_json, load_yaml
from nornir_jinja2.plugins.tasks import template_file, template_string
from nornir.core.task import AggregatedResult, Task, MultiResult

def htoolconfig(task):
    # Transform inventory data to configuration via a template file
    var = task.run(task=template_file,
                   name="htool templating",
                   template="htool-config.j2",
                   # current directory:
                   path=f"./config_templates/"
                   )
    # Save the compiled configuration into a host variable
    task.host["config"] = var.result
    task.host["config"] = task.host["config"].splitlines()
    task.run(task=netmiko_send_config, name="htool templating", config_commands=task.host["config"])

def main():
    # htool config
    task = nr.run(task=htoolconfig)
    print_result(task)

if __name__ == "__main__":
    main()
```

**Comment by ktbyers** [comment]
@jbl241987 Can you post the full exception stack trace?

I suspect the issue is that you the Nornir is calling the `enable()` method which for the Linux device type requires you execute `sudo -s`.

Note, netmiko_send_config is intended primarily for network devices and not for Linux. It is possible, you might need to work around some of the default patterns if you are using Netmiko on Linux (for example, create a custom task with more granular control of your Netmiko actions).

**Comment by jbl241987** [comment]
---- htool templating ** changed : False --------------------------------------- ERROR
Traceback (most recent call last):
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir_netmiko\tasks\netmiko_send_config.py", line 25, in netmiko_send_config
    net_connect.enable()
  File "C:\Users\jblokesh\Python37\lib\site-packages\netmiko\linux\linux_ssh.py", line 92, in enable
    self.set_base_prompt()
  File "C:\Users\jblokesh\Python37\lib\site-packages\netmiko\linux\linux_ssh.py", line 43, in set_base_prompt
    delay_factor=delay_factor,
  File "C:\Users\jblokesh\Python37\lib\site-packages\netmiko\base_connection.py", line 1141, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: '[sudo] password for jlokesh:'

^^^^ END htoolconfig ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by jbl241987** [comment]
@ktbyers thanks, any other library I can use for Linux in nornir.

**Comment by ktbyers** [comment]
Here are the main options:

1. Netmiko
   a. Add the `secret` so `sudo` works properly.
   b. Create a custom Netmiko task and avoid the `enable()` call
   c. Use netmiko_send_command (and not netmiko_send_config) and execute what you need to using that.
2. Use the Paramiko plugin that was in Nornir (not sure of the status of that in Nornir3, however, would have to search on that).


Regards, Kirk

**Comment by jbl241987** [comment]
@ktbyers I have the secret under hosts.yaml, but I am not sure how to use it. Till now I have used nornir for Cisco only but I want to list for commands on this server which I am also defining variables so using the Jinja2.

**Comment by jbl241987** [comment]
connection_options:
        netmiko:
          extras:
            secret: admin123

Traceback (most recent call last):
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\jblokesh\Python37\lib\site-packages\nornir_netmiko\tasks\netmiko_send_config.py", line 27, in netmiko_send_config
    result = net_connect.send_config_set(config_commands=config_commands, **kwargs)
  File "C:\Users\jblokesh\Python37\lib\site-packages\netmiko\linux\linux_ssh.py", line 51, in send_config_set
    config_commands=config_commands, exit_config_mode=exit_config_mode, **kwargs
TypeError: send_config_set() got an unexpected keyword argument 'secret'

**Comment by jbl241987** [comment]
I had a mistake, and corrected it. It is working now with just simple secret use.
thank you Kirk.
