### ISSUE TITLE
send_command with expected_string option sending self.RETURN in Netmiko instead of next command

### ISSUE THREAD

**Issue by mideoye** [ktbyers/nornir_netmiko#45]
Hi Kirk

Apologies if the answer to this is so obvious and I've made a mistake, but I'm struggling with an operation I'm looking to automate on a device using nornir_netmiko.

I am using nornir_netmiko to perform some operations on an OLT which has a CLI which runs like a linux shell. Device vendor is DZS and hardware is MXK-F series OLTs.

I am trying to modify user accounts on the device. Basically, here's the output of the operation when performed manually on CLI:

_olt3.lab$ user delete testuser
OK to delete this account? [yes] or [no]: yes
Account testuser deleted
olt3.lab$_

Now when I perform the same operation using nornir_netmiko using the code below:

task.host.name = olt3.lab
new_user = testuser

user_update=task.run(netmiko_send_command, command_string=f"user delete {new_user}", expect_string="yes", read_timeout=120)
print(user_update.result)
user_update[0].result += task.run(netmiko_send_command, command_string="yes")[0].result
if "deleted" in user_update[0].result:
    print(f"Account for user - '{new_user}' deleted.")
    logger.info("'%s' - Account for user - '%s' deleted.", task.host.name, new_user)
else:
    logger.error("'%s' - '%s'.", task.host.name, user_update[0].result)

I get the following output in the netmiko debug logs:

_07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'user delete testuser\n'
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: user delete testuser
OK to delete this account?
07-Nov-22 23:59:01 - netmiko - DEBUG - read_until_pattern(): Pattern found: (user\ delete\ testuser) user delete testuser
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel:  [yes] or [no]: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
**07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'\n'**
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
**07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
Account was not deleted.
olt3.lab$ 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_until_pattern(): Pattern found: ([\$\#]) 
Account was not deleted.
olt3.lab$
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - clear_buffer(): Clear buffer detects data in the channel
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - find_prompt(): [find_prompt()]: prompt is olt3.lab$
07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'yes\n'
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: yes
?Invalid command
olt3.lab$ 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_until_pattern(): Pattern found: (yes) yes
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - ERROR - user_exist(): 'olt3.lab' - 'OK to delete this account? [yes] or [no]: ?Invalid command'._**

Instead of:
_07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'user delete testuser\n'
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: user delete testuser
OK to delete this account?
07-Nov-22 23:59:01 - netmiko - DEBUG - read_until_pattern(): Pattern found: (user\ delete\ testuser) user delete testuser
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel:  [yes] or [no]: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
**07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'yes\n'**
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
**Account testuser deleted.**
olt3.lab$ 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_until_pattern(): Pattern found: ([\$\#]) 
olt3.lab$
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
07-Nov-22 23:59:01 - netmiko - DEBUG - find_prompt(): [find_prompt()]: prompt is olt3.lab$
07-Nov-22 23:59:01 - netmiko - DEBUG - wrapper_decorator(): write_channel: b'\n'
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel: 
olt3.lab$ EBUG - read_until_pattern(): Pattern found: (yes) yes
07-Nov-22 23:59:01 - netmiko - DEBUG - read_channel(): read_channel:_ 

Please can you have a look and let me know if I've done anything wrong here?

Package            Version
------------------ ---------
astroid            2.12.12
bcrypt             4.0.1
cffi               1.15.1
colorama           0.4.6
cryptography       38.0.1
dill               0.3.6
future             0.18.2
importlib-metadata 4.13.0
isort              5.10.1
lazy-object-proxy  1.8.0
mccabe             0.7.0
mypy-extensions    0.4.3
**_netmiko            4.1.2
nornir             3.3.0
nornir-netmiko     0.2.0
nornir-utils       0.2.0_**
ntc-templates      3.1.0
_**paramiko           2.11.0**_
pip                22.2.2
platformdirs       2.5.2
pycparser          2.21
pylint             2.15.5
PyNaCl             1.5.0
pyserial           3.5
python-dotenv      0.19.0
PyYAML             5.4.1
regex              2021.8.28
ruamel.yaml        0.17.21
ruamel.yaml.clib   0.2.7
scp                0.14.4
setuptools         65.3.0
six                1.16.0
tenacity           8.1.0
textfsm            1.1.2
tomli              2.0.1
tomlkit            0.11.6
typing_extensions  4.4.0
wheel              0.37.1
wrapt              1.14.1
zipp               3.10.0

Many thanks

'Mide

**Comment by ktbyers** [comment]
Try adding an expect_string to this line:

```python
user_update[0].result += task.run(netmiko_send_command, command_string="yes", expect_string="olt3")[0].result
```

**Comment by mideoye** [comment]
Thanks Kirk, that worked. Please can you explain why this resolved the issue? Many thanks

**Comment by ktbyers** [comment]
@mideoye When you execute send_command with no expect_string, Netmiko expects that it can work out the trailing prompt automatically by sending an <enter> key, but in your case, that extra sending of an <enter> key messes things up.

**Comment by mideoye** [comment]
> @mideoye When you execute send_command with no expect_string, Netmiko expects that it can work out the trailing prompt automatically by sending an <enter> key, but in your case, that extra sending of an <enter> key messes things up.

Thanks Kirk
