### ISSUE TITLE
Forward slash in netmiko_send_command and netmiko_send_config gives syntax error.

### ISSUE THREAD

**Issue by Rojin-dumre** [ktbyers/nornir_netmiko#49]
In my paloalto panos , when i use try to send command "show interface ethernet 1/1" it gives me syntax error. Other commands without forward slashes however work. No its not a configuration mode issue as I have made sure i am in the correct configuration mode. The command also works when i configure it through paltoalto system directly. What am I missing here? Is there any special way I need to send the command?

**Comment by Rojin-dumre** [comment]
The code i used is a simple sample code but here it is anyway:

```
output = nr.run(
    task=netmiko_send_config,
    config_commands=["exit", "show interface ethernet 1/1"]
        )

print_title("DEPLOYING AUTOMATED BASELINE CONFIGURATIONS")
print_result(output)
```

**Comment by ktbyers** [comment]
@Rojin-dumre Can you show an example of this happening with `send_command` and the full exception stack trace.
