### ISSUE TITLE
Update requirements for textfsm

### ISSUE THREAD

**Issue by VitMain** [ktbyers/nornir_netmiko#59]
Could you please update the requirements for the textfsm? 
Right now, it requires a 1.1.2 version. At the same time, we have textfsm version 1.1.3, and this version at the requirements for the netmiko. It means I can not update netmiko.

Thank you!

**Comment by dmulyalin** [comment]
Encountered same problem reported by poertry while trying to resolve dependencies:
```
#0 31.72     netmiko 4.2.0 depends on textfsm>=1.1.3
#0 31.72     nornir-netmiko 1.0.0 depends on textfsm==1.1.2
```

**Comment by ktbyers** [comment]
It is fixed in the nornir_netmiko `develop` branch (and you can just work around it during the installation process if you have are using the released version). Use the latest version of textfsm and nornir_netmiko should be fine.

**Comment by ktbyers** [comment]
@dmulyalin @VitMain  Just let me know if there is something I am missing, however, besides it being slightly annoying.
