### ISSUE TITLE
Does nornir-netmiko support netmiko version higher than > 4.0.0 ?

### ISSUE THREAD

**Issue by muffi-dn** [ktbyers/nornir_netmiko#61]

**Comment by ktbyers** [comment]
@muffi-dn Which version of nornir-netmiko are you using?

**Comment by muffi-dn** [comment]
I think I see the problem, I am using nornir-nautobot which restricts the version to `>=0.0.0 <0.1.0` which is causing it to install an older version of nornir-netmiko. I'll raise an issue there to see if they can upgrade. Sorry for the noise here, poetry dependencies are a lot to digest in one sitting. I'll close the issue here.
